<?php

/**
 * Created by PhpStorm.
 * User: keyhan
 * Date: 7/21/16
 * Time: 4:17 PM
 */


namespace khans\utils\actions\help;

use Yii;
use yii\base\Action;
use yii\helpers\Url;

/**
 * Centralized help action for all of applications
 * Reads help files generated by console application
 *
 * @package khans\utils\controllers
 * @version 2.1.1-980208
 * @since 1.0
 */
class HelpAction extends Action
{
    /**
     * @var array request parameters including module_id, controller_id & action_id
     */
    private $data;
    /**
     * @var string FQN of the help file
     */
    private $helpFile;
    /**
     * @var bool|array on file-not-found error contains details of data for admins
     */
    private $hint = false;

    /**
     * @inheritdoc
     */
    public function init()
    {
        $request = Yii::$app->request->get();
        $this->data = [
            'module'     => $request['module'],
            'controller' => $request['controller'],
            'action'     => $request['action'],
        ];

        $page = $this->data['module'] . '/' . $this->data['controller'] . '/' . $this->data['action'];
        if (Yii::$app->id == $this->data['module']) {
            $_page = '';
        } else {
            $_page = 'modules/' . $this->data['module'] . '/';
        }
        $_page .= 'views/helps/' . $this->data['controller'] . '-' . $this->data['action'];

        $helpPath = Url::to('@app') . '/';

        $this->helpFile = realpath($helpPath . $_page . '.md');
        if (YII_ENV == 'dev') {
            $this->hint = [
                'referer' => $page,
                'page'    => $_page,
                'file'    => $helpPath . $_page . '.md',
            ];
        }
        if (!file_exists($this->helpFile)) {
            $this->helpFile = realpath(__DIR__ . DIRECTORY_SEPARATOR . 'unknown' . '.md');
        }
    }

    /**
     * @inheritdoc
     */
    public function run()
    {
        return $this->controller->renderAjax('@khans/utils/actions/help/help-ajax', [
            'page'     => $this->data['module'] . '/' . $this->data['controller'] . '/' . $this->data['action'],
            'helpFile' => $this->helpFile,
            'hint'     => $this->hint,
        ]);
    }
}
