<?php

/**
 * Created by PhpStorm.
 * User: keyhan
 * Date: 7/21/16
 * Time: 4:17 PM
 */


namespace khans\utils\actions\help;

use Yii;
use yii\base\Action;
use yii\helpers\Url;

/**
 * Centralized help action for all of applications
 * Reads help files generated by console application
 *
 * @package khans\utils\controllers
 * @version 3.0.1-980223
 * @since 1.0
 */
class HelpAction extends Action
{
    /**
     * @var array request parameters including module_id, controller_id & action_id
     */
    private $helpPage;
    /**
     * @var string FQN of the help file
     */
    private $helpFile;
    /**
     * @var bool|array on file-not-found error contains details of data for admins
     */
    private $hint = false;

    /**
     * @inheritdoc
     */
    public function init()
    {
        $request = Yii::$app->request;
        
        $this->helpPage = str_replace($this->controller->id, '', $this->controller->getViewPath()) . 'helps/';
        $this->helpFile = $this->helpPage . $this->controller->id . '-' . $request->get('action') . '.md';
         if (!file_exists($this->helpFile)) {
            $this->helpFile = realpath(__DIR__ . DIRECTORY_SEPARATOR . 'unknown' . '.md');
        }
        if (YII_ENV == 'dev') {
            $this->hint = [
                'referer' => $request->referrer,
                'page'    => $this->helpPage . $this->controller->id . '-' . $request->get('action') . '.md',
                'file'    => $this->helpFile,
            ];
        }
    }

    /**
     * @inheritdoc
     */
    public function run()
    {
        return $this->controller->renderAjax('@khans/utils/actions/help/help-ajax', [
            'page'    => $this->helpPage,
            'helpFile' => $this->helpFile,
            'hint'     => $this->hint,
        ]);
    }
}
